version: 2
updates:
  # GitHub Actions (Own & Template)
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "template/*/"
    schedule:
      interval: "monthly"

  # npm (Own & Template Frontend/Infrastructure)
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "template/*/frontend/"
      - "template/*/infrastructure/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Template's Backend
  - package-ecosystem: "cargo"
    directories:
      - "template/*/backend/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Template's Docker Compose
  - package-ecosystem: "docker"
    directories:
      - "template/*/"
    schedule:
      interval: "daily"
      time: "09:15"
      timezone: "Europe/Berlin"
